@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTI4NzdjMTFjOGRlYjk3ZTAwNjE5YiIsImlhdCI6MTc0Mjg5OTA2OCwiZXhwIjoxNzQyOTAyNjY4fQ.Eo8A5Z5UCQG_RSZVyOClRn3CGJGzE8PT6YWPWxhgK0I

POST {{url}}/api/user/register
Content-Type: application/json

{
    "email": "eduardoruedadesantiago@gmail.com",
	"password":"12341234Abc$"
}

### 

PATCH {{url}}/api/user/validateEmail
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "code": 752840
}

### 

POST {{url}}/api/user/login
Content-Type: application/json

{
    "email": "eduardoruedadesantiago@gmail.com",
	"password":"12341234Abc$"
}


### 

PATCH {{url}}/api/user/editUserLogo
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="image"; filename="img.jpg"
Content-Type: image/jpg

< ./img.jpg
--Boundary--

### 

GET  {{url}}/api/user/getUserData
Content-Type: application/json
Authorization: Bearer {{token}}

### 

DELETE  {{url}}/api/user/deleteUser
Content-Type: application/json
Authorization: Bearer {{token}}