@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDJjNTlkNTQ0NTkwODk0MjAyNTcwZiIsImlhdCI6MTc0MjI5NTQ3OSwiZXhwIjoxNzQyMjk5MDc5fQ.HdgniyUX_HUmeQajSfzFGlWV5e40bSobl0ffzXdNNUs

POST {{url}}/api/user/register
Content-Type: application/json

{
    "email": "eduardoruedadesantiago@gmail.com",
	"password":"12341234Abc$"
}

### 

POST {{url}}/api/user/login
Content-Type: application/json

{
    "email": "eduardoruedadesantiago@gmail.com",
	"password":"12341234Abc$"
}

### 

DELETE  {{url}}/api/user/deleteUser
Content-Type: application/json
Authorization: Bearer {{token}}